"""`PytestOutputParser` against recorded real pytest output (E8-F2-T4).

The fixtures under `tests/fixtures/pytest_output/` were generated by running pytest
9.x with the exact args `TestExecutionService` uses (`-q --tb=short -p no:cacheprovider`)
against `tests/fixtures/sample_repo` and committed verbatim. An approximated fixture
would teach the parser to handle output that does not exist.
"""

from __future__ import annotations

from pathlib import Path

import pytest

from devmind.schemas.sandbox import CommandResult
from devmind.services.pytest_output_parser import PytestOutputParser

_FIXTURES = Path(__file__).parents[1] / "fixtures" / "pytest_output"


def _result(name: str, *, exit_code: int) -> CommandResult:
    return CommandResult(
        argv=("python", "-m", "pytest"),
        exit_code=exit_code,
        stdout=(_FIXTURES / name).read_text(encoding="utf-8"),
        stderr="",
        duration_seconds=1.0,
    )


@pytest.fixture
def parser() -> PytestOutputParser:
    return PytestOutputParser()


def test_all_passed(parser: PytestOutputParser) -> None:
    report = parser.parse(_result("all_passed.txt", exit_code=0))
    assert report.succeeded is True
    assert (report.passed, report.failed, report.errors) == (2, 0, 0)
    assert report.failures == ()
    assert report.collection_error is None


def test_assertion_failure(parser: PytestOutputParser) -> None:
    report = parser.parse(_result("assertion_failure.txt", exit_code=1))
    assert report.succeeded is False
    assert (report.passed, report.failed, report.errors) == (0, 2, 0)
    node_ids = {f.node_id for f in report.failures}
    assert node_ids == {
        "tests/test_assertion.py::test_add_two_and_two",
        "tests/test_assertion.py::test_add_ten_and_five",
    }
    first = next(f for f in report.failures if f.node_id.endswith("test_add_two_and_two"))
    assert first.file == "tests/test_assertion.py"
    assert first.line == 5
    assert "assert 0 == 4" in first.message


def test_multiple_failures_mixed_with_passes(parser: PytestOutputParser) -> None:
    report = parser.parse(_result("multiple_failures.txt", exit_code=1))
    assert (report.passed, report.failed, report.errors) == (1, 3, 0)
    assert report.total == 4
    by_id = {f.node_id.split("::")[-1]: f for f in report.failures}
    assert set(by_id) == {"test_add_broken", "test_divide_broken", "test_divide_by_zero"}
    assert by_id["test_divide_by_zero"].exception_type == "ZeroDivisionError"


def test_import_error_is_a_collection_error(parser: PytestOutputParser) -> None:
    report = parser.parse(_result("import_error.txt", exit_code=2))
    assert report.succeeded is False
    assert report.collection_error is not None
    assert "ModuleNotFoundError" in report.collection_error
    assert report.failures == ()  # no per-test node ids when collection fails


def test_collection_syntax_error(parser: PytestOutputParser) -> None:
    report = parser.parse(_result("collection_error.txt", exit_code=2))
    assert report.succeeded is False
    assert report.collection_error is not None
    assert "SyntaxError" in report.collection_error


def test_fixture_setup_error_is_an_error_not_a_collection_error(
    parser: PytestOutputParser,
) -> None:
    report = parser.parse(_result("fixture_error.txt", exit_code=1))
    assert report.succeeded is False
    assert report.collection_error is None
    assert report.errors == 1
    assert len(report.failures) == 1
    failure = report.failures[0]
    assert failure.node_id == "tests/test_fixture_err.py::test_uses_broken_fixture"
    assert failure.exception_type == "RuntimeError"
    assert "fixture setup blew up" in failure.message


def test_empty_suite(parser: PytestOutputParser) -> None:
    report = parser.parse(_result("empty_suite.txt", exit_code=5))
    assert (report.total, report.passed, report.failed, report.errors) == (0, 0, 0, 0)
    assert report.unparseable is False
    assert report.timed_out is False
